<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>KandaEu.Volejbal.TestsForLocalDebugging</AssemblyName>
		<RootNamespace>KandaEu.Volejbal.TestsForLocalDebugging</RootNamespace>
		<PublishDir>obj\$(Configuration)\publish</PublishDir>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<EnableMSTestRunner>true</EnableMSTestRunner>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Cosmos" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="MSTest" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataLayer\DataLayer.csproj" />
		<ProjectReference Include="..\DependencyInjection\DependencyInjection.csproj" />
		<ProjectReference Include="..\Model\Model.csproj" />
		<ProjectReference Include="..\Services\Services.csproj" />
	</ItemGroup>

</Project>
