//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace KandaEu.Volejbal.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeVzkazDataSource : FakeDataSource<KandaEu.Volejbal.Model.Vzkaz>, KandaEu.Volejbal.DataLayer.DataSources.IVzkazDataSource
{
	public FakeVzkazDataSource(params KandaEu.Volejbal.Model.Vzkaz[] data)
		: this((IEnumerable<KandaEu.Volejbal.Model.Vzkaz>)data)
	{			
	}

	public FakeVzkazDataSource(IEnumerable<KandaEu.Volejbal.Model.Vzkaz> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
