<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>KandaEu.Volejbal.Services</AssemblyName>
		<RootNamespace>KandaEu.Volejbal.Services</RootNamespace>

		<!-- RID z publishe Api musí protéct až do DataLayeru, důvod viz DataLayer.csproj. -->
		<IsRidAgnostic>false</IsRidAgnostic>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Havit.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataLayer\DataLayer.csproj" />
		<ProjectReference Include="..\Model\Model.csproj" />
	</ItemGroup>

</Project>
