// <auto-generated />
using System;
using KandaEu.Volejbal.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KandaEu.Volejbal.Entity.Migrations
{
    [DbContext(typeof(VolejbalDbContext))]
    [Migration("20190218093705_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Havit.Data.EntityFrameworkCore.Model.DataSeedVersion", b =>
                {
                    b.Property<string>("ProfileName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250);

                    b.Property<string>("Version");

                    b.HasKey("ProfileName")
                        .HasName("PK_DataSeed");

                    b.ToTable("__DataSeed");
                });

            modelBuilder.Entity("KandaEu.Volejbal.Model.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Osoba");
                });

            modelBuilder.Entity("KandaEu.Volejbal.Model.Prihlaska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumPrihlaseni");

                    b.Property<DateTime?>("Deleted");

                    b.Property<int>("OsobaId");

                    b.Property<int>("TerminId");

                    b.HasKey("Id");

                    b.HasIndex("OsobaId");

                    b.HasIndex("TerminId", "OsobaId", "Deleted")
                        .IsUnique()
                        .HasName("UIDX_Prihlaska_TerminId_OsobaId_Deleted");

                    b.ToTable("Prihlaska");
                });

            modelBuilder.Entity("KandaEu.Volejbal.Model.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum");

                    b.Property<DateTime?>("Deleted");

                    b.HasKey("Id");

                    b.HasIndex("Datum", "Deleted")
                        .IsUnique()
                        .HasName("UIDX_Termin_Datum_Deleted");

                    b.ToTable("Termin");
                });

            modelBuilder.Entity("KandaEu.Volejbal.Model.Vzkaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AutorId");

                    b.Property<DateTime>("DatumVlozeni");

                    b.Property<DateTime?>("Deleted");

                    b.Property<string>("Zprava")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Vzkaz");
                });

            modelBuilder.Entity("KandaEu.Volejbal.Model.Prihlaska", b =>
                {
                    b.HasOne("KandaEu.Volejbal.Model.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KandaEu.Volejbal.Model.Termin", "Termin")
                        .WithMany()
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("KandaEu.Volejbal.Model.Vzkaz", b =>
                {
                    b.HasOne("KandaEu.Volejbal.Model.Osoba", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
