//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DependencyInjection;
using Havit.Data.EntityFrameworkCore.Patterns.Infrastructure;
using Havit.Data.EntityFrameworkCore.Patterns.Repositories;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.DataSources;
using Havit.Data.Patterns.Infrastructure;
using Havit.Data.Patterns.Repositories;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

namespace KandaEu.Volejbal.DataLayer;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static partial class DataLayerServiceExtensions
{
	public static IServiceCollection AddDataLayerServices(this IServiceCollection services, ComponentRegistrationOptions options = null)
	{
		services.AddDataLayerCoreServices(options);
	
		AddDataSources(services);
		AddRepositories(services);
		AddDataEntries(services);
		AddEntityKeyAccessors(services);

		return services;
	}

	private static void AddDataSources(IServiceCollection services)
	{
		services.TryAddTransient<KandaEu.Volejbal.DataLayer.DataSources.IOsobaDataSource, KandaEu.Volejbal.DataLayer.DataSources.OsobaDbDataSource>();
		services.TryAddTransient<IDataSource<KandaEu.Volejbal.Model.Osoba>, KandaEu.Volejbal.DataLayer.DataSources.OsobaDbDataSource>();

		services.TryAddTransient<KandaEu.Volejbal.DataLayer.DataSources.IPrihlaskaDataSource, KandaEu.Volejbal.DataLayer.DataSources.PrihlaskaDbDataSource>();
		services.TryAddTransient<IDataSource<KandaEu.Volejbal.Model.Prihlaska>, KandaEu.Volejbal.DataLayer.DataSources.PrihlaskaDbDataSource>();

		services.TryAddTransient<KandaEu.Volejbal.DataLayer.DataSources.ITerminDataSource, KandaEu.Volejbal.DataLayer.DataSources.TerminDbDataSource>();
		services.TryAddTransient<IDataSource<KandaEu.Volejbal.Model.Termin>, KandaEu.Volejbal.DataLayer.DataSources.TerminDbDataSource>();

		services.TryAddTransient<KandaEu.Volejbal.DataLayer.DataSources.IVzkazDataSource, KandaEu.Volejbal.DataLayer.DataSources.VzkazDbDataSource>();
		services.TryAddTransient<IDataSource<KandaEu.Volejbal.Model.Vzkaz>, KandaEu.Volejbal.DataLayer.DataSources.VzkazDbDataSource>();

	}

	private static void AddRepositories(IServiceCollection services)
	{
		services.TryAddScoped<KandaEu.Volejbal.DataLayer.Repositories.IOsobaRepository, KandaEu.Volejbal.DataLayer.Repositories.OsobaDbRepository>();
		services.TryAddScoped<IRepository<KandaEu.Volejbal.Model.Osoba, System.Int32>>(sp => sp.GetRequiredService<KandaEu.Volejbal.DataLayer.Repositories.IOsobaRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<KandaEu.Volejbal.Model.Osoba, System.Int32>, KandaEu.Volejbal.DataLayer.Repositories.OsobaDbRepositoryQueryProvider>();

		services.TryAddScoped<KandaEu.Volejbal.DataLayer.Repositories.IPrihlaskaRepository, KandaEu.Volejbal.DataLayer.Repositories.PrihlaskaDbRepository>();
		services.TryAddScoped<IRepository<KandaEu.Volejbal.Model.Prihlaska, System.Int32>>(sp => sp.GetRequiredService<KandaEu.Volejbal.DataLayer.Repositories.IPrihlaskaRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<KandaEu.Volejbal.Model.Prihlaska, System.Int32>, KandaEu.Volejbal.DataLayer.Repositories.PrihlaskaDbRepositoryQueryProvider>();

		services.TryAddScoped<KandaEu.Volejbal.DataLayer.Repositories.ITerminRepository, KandaEu.Volejbal.DataLayer.Repositories.TerminDbRepository>();
		services.TryAddScoped<IRepository<KandaEu.Volejbal.Model.Termin, System.Int32>>(sp => sp.GetRequiredService<KandaEu.Volejbal.DataLayer.Repositories.ITerminRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<KandaEu.Volejbal.Model.Termin, System.Int32>, KandaEu.Volejbal.DataLayer.Repositories.TerminDbRepositoryQueryProvider>();

		services.TryAddScoped<KandaEu.Volejbal.DataLayer.Repositories.IVzkazRepository, KandaEu.Volejbal.DataLayer.Repositories.VzkazDbRepository>();
		services.TryAddScoped<IRepository<KandaEu.Volejbal.Model.Vzkaz, System.Int32>>(sp => sp.GetRequiredService<KandaEu.Volejbal.DataLayer.Repositories.IVzkazRepository>());
		services.TryAddSingleton<IRepositoryQueryProvider<KandaEu.Volejbal.Model.Vzkaz, System.Int32>, KandaEu.Volejbal.DataLayer.Repositories.VzkazDbRepositoryQueryProvider>();

	}

	private static void AddDataEntries(IServiceCollection services)
	{
	}

	private static void AddEntityKeyAccessors(IServiceCollection services)
	{
		services.TryAddTransient<IEntityKeyAccessor<KandaEu.Volejbal.Model.Osoba, System.Int32>, DbEntityKeyAccessor<KandaEu.Volejbal.Model.Osoba, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<KandaEu.Volejbal.Model.Prihlaska, System.Int32>, DbEntityKeyAccessor<KandaEu.Volejbal.Model.Prihlaska, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<KandaEu.Volejbal.Model.Termin, System.Int32>, DbEntityKeyAccessor<KandaEu.Volejbal.Model.Termin, System.Int32>>();
		services.TryAddTransient<IEntityKeyAccessor<KandaEu.Volejbal.Model.Vzkaz, System.Int32>, DbEntityKeyAccessor<KandaEu.Volejbal.Model.Vzkaz, System.Int32>>();
	}
}
