//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace KandaEu.Volejbal.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakePrihlaskaDataSource : FakeDataSource<KandaEu.Volejbal.Model.Prihlaska>, KandaEu.Volejbal.DataLayer.DataSources.IPrihlaskaDataSource
{
	public FakePrihlaskaDataSource(params KandaEu.Volejbal.Model.Prihlaska[] data)
		: this((IEnumerable<KandaEu.Volejbal.Model.Prihlaska>)data)
	{			
	}

	public FakePrihlaskaDataSource(IEnumerable<KandaEu.Volejbal.Model.Prihlaska> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
