//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace KandaEu.Volejbal.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeOsobaDataSource : FakeDataSource<KandaEu.Volejbal.Model.Osoba>, KandaEu.Volejbal.DataLayer.DataSources.IOsobaDataSource
{
	public FakeOsobaDataSource(params KandaEu.Volejbal.Model.Osoba[] data)
		: this((IEnumerable<KandaEu.Volejbal.Model.Osoba>)data)
	{			
	}

	public FakeOsobaDataSource(IEnumerable<KandaEu.Volejbal.Model.Osoba> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
