//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace KandaEu.Volejbal.DataLayer.DataSources.Fakes;

[Fake]
[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class FakeTerminDataSource : FakeDataSource<KandaEu.Volejbal.Model.Termin>, KandaEu.Volejbal.DataLayer.DataSources.ITerminDataSource
{
	public FakeTerminDataSource(params KandaEu.Volejbal.Model.Termin[] data)
		: this((IEnumerable<KandaEu.Volejbal.Model.Termin>)data)
	{			
	}

	public FakeTerminDataSource(IEnumerable<KandaEu.Volejbal.Model.Termin> data, ISoftDeleteManager softDeleteManager = null)
		: base(data, softDeleteManager)
	{
	}
}
