//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Entity.Patterns.DataSources.Fakes;
using Havit.Data.Entity.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.NewProjectTemplate.DataLayer.DataSources.Security.Fakes
{
	[Fake]
	[System.CodeDom.Compiler.GeneratedCode("Havit.Entity.CodeGenerator", "2.0")]
	public class FakeLoginAccountDataSource : FakeDataSource<Havit.NewProjectTemplate.Model.Security.LoginAccount>, Havit.NewProjectTemplate.DataLayer.DataSources.Security.ILoginAccountDataSource
	{
		public FakeLoginAccountDataSource(params Havit.NewProjectTemplate.Model.Security.LoginAccount[] data)
			: this((IEnumerable<Havit.NewProjectTemplate.Model.Security.LoginAccount>)data)
		{			
		}

		public FakeLoginAccountDataSource(IEnumerable<Havit.NewProjectTemplate.Model.Security.LoginAccount> data, ISoftDeleteManager softDeleteManager = null)
			: base(data, softDeleteManager)
		{
		}
	}
}