//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.Repositories;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Microsoft.EntityFrameworkCore;
using DbContext = Havit.Data.EntityFrameworkCore.DbContext;

namespace KandaEu.Volejbal.DataLayer.Repositories;

internal class TerminDbRepositoryQueryProvider : IRepositoryQueryProvider<KandaEu.Volejbal.Model.Termin, System.Int32>
{
	private readonly Func<DbContext, System.Int32, KandaEu.Volejbal.Model.Termin> _getObjectQuery;
	private readonly Func<DbContext, System.Int32, CancellationToken, Task<KandaEu.Volejbal.Model.Termin>> _getObjectAsyncQuery;
	private readonly Func<DbContext, System.Int32[], IEnumerable<KandaEu.Volejbal.Model.Termin>> _getObjectsQuery;
	private readonly Func<DbContext, System.Int32[], IAsyncEnumerable<KandaEu.Volejbal.Model.Termin>> _getObjectsAsyncQuery;

	public TerminDbRepositoryQueryProvider()
	{
		_getObjectQuery = EF.CompileQuery((DbContext dbContext, System.Int32 id) => dbContext
			.Set<KandaEu.Volejbal.Model.Termin>()
			.TagWith("TerminDbRepository.GetObject")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32 id, CancellationToken cancellationToken) => dbContext
			.Set<KandaEu.Volejbal.Model.Termin>()
			.TagWith("TerminDbRepository.GetObjectAsync")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectsQuery = EF.CompileQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<KandaEu.Volejbal.Model.Termin>()
			.TagWith("TerminDbRepository.GetObjects")
			.Where(entity => ids.Contains(entity.Id)));

		_getObjectsAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<KandaEu.Volejbal.Model.Termin>()
			.TagWith("TerminDbRepository.GetObjectsAsync")
			.Where(entity => ids.Contains(entity.Id)));
	}

	public Func<DbContext, System.Int32, KandaEu.Volejbal.Model.Termin> GetGetObjectQuery() => _getObjectQuery;
	public Func<DbContext, System.Int32, CancellationToken, Task<KandaEu.Volejbal.Model.Termin>> GetGetObjectAsyncQuery() => _getObjectAsyncQuery;
	public Func<DbContext, System.Int32[], IEnumerable<KandaEu.Volejbal.Model.Termin>> GetGetObjectsQuery() => _getObjectsQuery;
	public Func<DbContext, System.Int32[], IAsyncEnumerable<KandaEu.Volejbal.Model.Termin>> GetGetObjectsAsyncQuery() => _getObjectsAsyncQuery;
}
