<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>KandaEu.Volejbal.Facades</AssemblyName>
		<RootNamespace>KandaEu.Volejbal.Facades</RootNamespace>

		<!-- RID z publishe Api musí protéct až do DataLayeru, důvod viz DataLayer.csproj. -->
		<IsRidAgnostic>false</IsRidAgnostic>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Havit.VolejbalApp.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Havit.Core" />
		<PackageReference Include="Havit.Extensions.DependencyInjection.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Contracts\Contracts.csproj" />
		<ProjectReference Include="..\DataLayer\DataLayer.csproj" />
		<ProjectReference Include="..\Model\Model.csproj" />
		<ProjectReference Include="..\Services\Services.csproj" />
	</ItemGroup>

</Project>
