//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Entity.Patterns.DataSources.Fakes;
using Havit.Data.Entity.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.NewProjectTemplate.DataLayer.DataSources.Common.Fakes
{
	[Fake]
	[System.CodeDom.Compiler.GeneratedCode("Havit.Entity.CodeGenerator", "2.0")]
	public class FakeApplicationSettingsDataSource : FakeDataSource<Havit.NewProjectTemplate.Model.Common.ApplicationSettings>, Havit.NewProjectTemplate.DataLayer.DataSources.Common.IApplicationSettingsDataSource
	{
		public FakeApplicationSettingsDataSource(params Havit.NewProjectTemplate.Model.Common.ApplicationSettings[] data)
			: this((IEnumerable<Havit.NewProjectTemplate.Model.Common.ApplicationSettings>)data)
		{			
		}

		public FakeApplicationSettingsDataSource(IEnumerable<Havit.NewProjectTemplate.Model.Common.ApplicationSettings> data, ISoftDeleteManager softDeleteManager = null)
			: base(data, softDeleteManager)
		{
		}
	}
}