<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>KandaEu.Volejbal.DependencyInjection</AssemblyName>
		<RootNamespace>KandaEu.Volejbal.DependencyInjection</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Havit.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DataLayer\DataLayer.csproj" />
		<ProjectReference Include="..\Entity\Entity.csproj" />
		<ProjectReference Include="..\Facades\Facades.csproj" />
		<ProjectReference Include="..\Model\Model.csproj" />
		<ProjectReference Include="..\Services\Services.csproj" />
	</ItemGroup>

</Project>
