//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Entity;
using Havit.Data.Entity.Patterns.DataSources;
using Havit.Data.Entity.Patterns.SoftDeletes;

namespace Havit.NewProjectTemplate.DataLayer.DataSources.Localizations
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Entity.CodeGenerator", "2.0")]
	public class LanguageDbDataSource : DbDataSource<Havit.NewProjectTemplate.Model.Localizations.Language>, ILanguageDataSource
	{
		public LanguageDbDataSource(IDbContext dbContext, ISoftDeleteManager softDeleteManager)
			: base(dbContext, softDeleteManager)
		{
		}
	}
}