//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Entity;
using Havit.Data.Entity.Patterns.Repositories;
using Havit.Data.Entity.Patterns.SoftDeletes;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.DataLoaders;

namespace Havit.NewProjectTemplate.DataLayer.Repositories.Security
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Entity.CodeGenerator", "2.0")]
	public partial class LoginAccountDbRepository : LoginAccountDbRepositoryBase, ILoginAccountRepository
	{
		public LoginAccountDbRepository(IDbContext dbContext, Havit.NewProjectTemplate.DataLayer.DataSources.Security.ILoginAccountDataSource dataSource, IDataLoader dataLoader, IDataLoaderAsync dataLoaderAsync, ISoftDeleteManager softDeleteManager)
			: base(dbContext, dataSource, dataLoader, dataLoaderAsync, softDeleteManager)
		{
		}
	}
}