//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KandaEu.Volejbal.Model.Metadata;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static class OsobaMetadata
{
	public const int EmailMaxLength = 50;
	public const int JmenoMaxLength = 50;
	public const int PrijmeniMaxLength = 50;
}
