<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<AssemblyName>KandaEu.Volejbal.Web.Client</AssemblyName>
		<RootNamespace>KandaEu.Volejbal.Web.Client</RootNamespace>

		<!-- čeština není v defaultních ICU shardech (EFIGS), bez plných dat by nefungovalo české formátování datumů -->
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Blazored.LocalStorage" />
		<PackageReference Include="Havit.Blazor.Components.Web.Bootstrap" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Microsoft.Extensions.Localization" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Contracts\Contracts.csproj" />
	</ItemGroup>

</Project>
